<%
    session.setAttribute("username", null);
    session.invalidate();
%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Home page</title>
        <meta charset="utf-8">
        <meta name="description" content="Online Bill Payment">
        <meta name="keywords" content="homepage,sliding picture,Bangladesh Power Development Board(BPDB) history">
        <meta name="author" content="Md. Sohel Rana">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="refresh" content="60">
        <link rel="shortcut icon" href="image/logo.png" />
        <link rel="stylesheet" href="css/home.css" type="text/css"/>
    </head>
    <body>
        <div class="page_margin">


            <div class="header_container">
                <img src="image/logo.png" alt="Header Logo" class="image1">

                <div class="header_content">
                    <h1>Bangladesh Power Development Board</h1>
                </div>


            </div>

            <ul>
                <li><a class="active" href="">Home</a></li>
                <li><a href="RegistrationForm">Registration</a></li>
                <li><a href="BillPay">Bill Pay</a></li>
                <li><a href="billReceipt_login">Bill Receipt</a></li>
                <li><a href="Admin_login">Admin</a></li>
                <li style="float:right"><a href="about">About</a></li>
            </ul>

            <div id= "slider">
                <figure>
                    <img src = "slideImage/1.jpg">
                    <img src = "slideImage/2.jpg">
                    <img src = "slideImage/3.jpg">
                    <img src = "slideImage/4.jpg">
                    <img src = "slideImage/5.jpg">
                </figure>
            </div>

            <div class="div_container">

                <h2>Welcome to BPDB</h2> 
                <p>Bangladesh Power Development Board (BPDB) is a  statutory body created in May 1,
                    1972, by presidential Order No. 59 after bifurcation of erstwhile Bangladesh Water and Power Development Authority. BPDB started
                    its operation with Installed Generation capacity of only 200 MW. Installed Generation capacity including Captive Power (as on December, 2017)
                    has increased to (13,846+2,200) = 16,046 MW.<br><br>As part of reform and restructuring a number of Generation and Distribution companies have been created.
                    The subsidiaries of BPDB are:<br><br>- Ashuganj Power Station Company Ltd. (APSCL)<br>- Electricity Generation Company of Bangladesh (EGCB)<br> 

                    - North West Power Generation Company Ltd. (NWPGCL) <br>

                    - West Zone Power Distribution Company Ltd. (WZPDCL)<br><br>The BPDB is responsible for major portion of generation and distribution of electricity mainly
                    in urban areas except Dhaka and West Zone of the country. The Board is under the Power Division of the Ministry of power,
                    Energy and Mineral Resources, Government of Bangladesh<br><br>BPDB has taken a massive capacity expansion plan to add
                    about 11600 MW Generation capacity in next 5 years to achieve 24000 MW Capacity according to PSMP-2010 by 2021 with the
                    aim to provide quality and reliable electricity to all the people of Country for desired economic and social development.
                    The power system has been expanded to keep pace with the fast growing demand</p> 


            </div>

            <div class="div_container">

                <h2>History of BPDB</h2> 
                <p>At the time of partition of Indo-pak sub-continent,
                    in the year 1947 when the British colonial rulers left, power generation and distribution of this
                    part of the country were in the hands of some private companies. The power supply to then 17 provincial
                    districts was within the township in a limited way. The generation voltage was 400 volts. Power used to be
                    supplied to most of the districts during nighttime only. Only exception was Dhaka City where power used to be
                    supplied by two 1500 kW generators and the generation voltage was 6600 volts and this was the highest supply voltage.
                    There was no long distance transmission lines. Besides power used to be generated by some industries (tea, sugar and textiles) and railway workshops.
                    Dhakeswari Cotton Mills, Pahartali Railway workshop, Saidpur Railway workshop and Sugar Mills were amongst them.
                    In aggregate the generation capacity of the country was 21 MW. The generation capacity of the power utility companies
                    together was only 7 (seven) MW and there was no transmission system.</p> 

            </div>

            <div class="div_container">

                <h2>Vision & Mission</h2> 
                <p><b>Vission</b><br><br>-To deliver uninterrupted quality power to all.<br><br>
                    <b>Mission</b><br><br>-To secure continuous growth of electricity for sustainable development and ensure customer satisfaction.</p> 

            </div>

            <footer>Copyright &copy; Sohel Rana</footer>
        </div> 
    </body>
</html>
